name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1' # run "At 08:00 on Monday"ma

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOLANGCI_LINT_VERSION: v1.56.1

    strategy:
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Linter
        run: |
          make linter

      - name: Test
        run: |
          make test